# -*- coding: utf-8 -*-
"""greetingapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IeBdD-KyxVx1Q6lYUtt353cR65b2x0sz
"""

import streamlit as st
st.title(" 👋مرحبا بكم في موقعنا الاول باستخدام ستريم ليت")
name=st.text_input("ما هو اسمك 🤏")
if name:
  st.write("مرحبا بك يا",name,"نورت الموقع")
  st.balloons()